# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
logo_path: "/s17/images/S17.png"
title: "S-17"
url: "http://s-17.fr" # the base hostname & protocol for your site
blocs:
  -  '1'
  -  '2'
  -  '3'
  -  '4'
images:
  -  '1'
  -  '2'
  -  '3'
  -  '4'
